// This file will be auto-generated by Supabase CLI in the future.
// For now, we use a placeholder that you can extend manually.
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts

export interface Database {
  public: {
    Tables: {
      // Tables will be added here as you create them in Supabase
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
